kafka:
  hosts: localhost:9092
  receiver :
    deogicorgi-topic-1:
      name : deogicorgi-topic-1
      topic : deogicorgi-topic-1
      groupId : deogicorgi-topic-1
    deogicorgi-topic-2:
      name : deogicorgi-topic-2
      topic : deogicorgi-topic-2
      groupId : deogicorgi-topic-2
